//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsApplication.com.quantiguous {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.quantiguous.com/services", ConfigurationName="com.quantiguous.DomesticRemittanceByPartnerService")]
    public interface DomesticRemittanceByPartnerService {
        
        // CODEGEN: Generating message contract since the operation remit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/remit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FormsApplication.com.quantiguous.remitResponse1 remit(FormsApplication.com.quantiguous.remitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/remit", ReplyAction="*")]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.remitResponse1> remitAsync(FormsApplication.com.quantiguous.remitRequest request);
        
        // CODEGEN: Generating message contract since the operation getBalance is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getBalance" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FormsApplication.com.quantiguous.getBalanceResponse1 getBalance(FormsApplication.com.quantiguous.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getBalance" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getBalanceResponse1> getBalanceAsync(FormsApplication.com.quantiguous.getBalanceRequest request);
        
        // CODEGEN: Generating message contract since the operation getRemittanceStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getRemitta" +
            "nceStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FormsApplication.com.quantiguous.getRemittanceStatusResponse1 getRemittanceStatus(FormsApplication.com.quantiguous.getRemittanceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getRemitta" +
            "nceStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getRemittanceStatusResponse1> getRemittanceStatusAsync(FormsApplication.com.quantiguous.getRemittanceStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation getTransactions is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getTransac" +
            "tions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FormsApplication.com.quantiguous.getTransactionsResponse1 getTransactions(FormsApplication.com.quantiguous.getTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.quantiguous.com/services/DomesticRemittanceByPartnerService/getTransac" +
            "tions", ReplyAction="*")]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getTransactionsResponse1> getTransactionsAsync(FormsApplication.com.quantiguous.getTransactionsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class remit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueRequestNoField;
        
        private string partnerCodeField;
        
        private string customerIDField;
        
        private string debitAccountNoField;
        
        private string remitterAccountNoField;
        
        private string remitterIFSCField;
        
        private string remitterNameField;
        
        private AddressType remitterAddressField;
        
        private contactType remitterContactField;
        
        private string beneficiaryNameField;
        
        private AddressType beneficiaryAddressField;
        
        private contactType beneficiaryContactField;
        
        private string beneficiaryAccountNoField;
        
        private string beneficiaryIFSCField;
        
        private transferTypeType transferTypeField;
        
        private currencyCodeType transferCurrencyCodeField;
        
        private decimal transferAmountField;
        
        private string remitterToBeneficiaryInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueRequestNo {
            get {
                return this.uniqueRequestNoField;
            }
            set {
                this.uniqueRequestNoField = value;
                this.RaisePropertyChanged("uniqueRequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=2)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
                this.RaisePropertyChanged("partnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string debitAccountNo {
            get {
                return this.debitAccountNoField;
            }
            set {
                this.debitAccountNoField = value;
                this.RaisePropertyChanged("debitAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string remitterAccountNo {
            get {
                return this.remitterAccountNoField;
            }
            set {
                this.remitterAccountNoField = value;
                this.RaisePropertyChanged("remitterAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string remitterIFSC {
            get {
                return this.remitterIFSCField;
            }
            set {
                this.remitterIFSCField = value;
                this.RaisePropertyChanged("remitterIFSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string remitterName {
            get {
                return this.remitterNameField;
            }
            set {
                this.remitterNameField = value;
                this.RaisePropertyChanged("remitterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public AddressType remitterAddress {
            get {
                return this.remitterAddressField;
            }
            set {
                this.remitterAddressField = value;
                this.RaisePropertyChanged("remitterAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public contactType remitterContact {
            get {
                return this.remitterContactField;
            }
            set {
                this.remitterContactField = value;
                this.RaisePropertyChanged("remitterContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string beneficiaryName {
            get {
                return this.beneficiaryNameField;
            }
            set {
                this.beneficiaryNameField = value;
                this.RaisePropertyChanged("beneficiaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public AddressType beneficiaryAddress {
            get {
                return this.beneficiaryAddressField;
            }
            set {
                this.beneficiaryAddressField = value;
                this.RaisePropertyChanged("beneficiaryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public contactType beneficiaryContact {
            get {
                return this.beneficiaryContactField;
            }
            set {
                this.beneficiaryContactField = value;
                this.RaisePropertyChanged("beneficiaryContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string beneficiaryAccountNo {
            get {
                return this.beneficiaryAccountNoField;
            }
            set {
                this.beneficiaryAccountNoField = value;
                this.RaisePropertyChanged("beneficiaryAccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string beneficiaryIFSC {
            get {
                return this.beneficiaryIFSCField;
            }
            set {
                this.beneficiaryIFSCField = value;
                this.RaisePropertyChanged("beneficiaryIFSC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public transferTypeType transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public currencyCodeType transferCurrencyCode {
            get {
                return this.transferCurrencyCodeField;
            }
            set {
                this.transferCurrencyCodeField = value;
                this.RaisePropertyChanged("transferCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string remitterToBeneficiaryInfo {
            get {
                return this.remitterToBeneficiaryInfoField;
            }
            set {
                this.remitterToBeneficiaryInfoField = value;
                this.RaisePropertyChanged("remitterToBeneficiaryInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string postalCodeField;
        
        private string cityField;
        
        private string stateOrProvinceField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string stateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
                this.RaisePropertyChanged("stateOrProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class transactionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime transactionDateTimeField;
        
        private transactionTypeType transactionType1Field;
        
        private decimal amountField;
        
        private string narrativeField;
        
        private string referenceNoField;
        
        private decimal balanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime transactionDateTime {
            get {
                return this.transactionDateTimeField;
            }
            set {
                this.transactionDateTimeField = value;
                this.RaisePropertyChanged("transactionDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transactionType", Order=1)]
        public transactionTypeType transactionType1 {
            get {
                return this.transactionType1Field;
            }
            set {
                this.transactionType1Field = value;
                this.RaisePropertyChanged("transactionType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string narrative {
            get {
                return this.narrativeField;
            }
            set {
                this.narrativeField = value;
                this.RaisePropertyChanged("narrative");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum transactionTypeType {
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class dateRangeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime fromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("fromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime toDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("toDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class transactionStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private transactionStatusTypeStatusCode statusCodeField;
        
        private string subStatusCodeField;
        
        private string bankReferenceNoField;
        
        private string beneficiaryReferenceNoField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public transactionStatusTypeStatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string subStatusCode {
            get {
                return this.subStatusCodeField;
            }
            set {
                this.subStatusCodeField = value;
                this.RaisePropertyChanged("subStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string bankReferenceNo {
            get {
                return this.bankReferenceNoField;
            }
            set {
                this.bankReferenceNoField = value;
                this.RaisePropertyChanged("bankReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string beneficiaryReferenceNo {
            get {
                return this.beneficiaryReferenceNoField;
            }
            set {
                this.beneficiaryReferenceNoField = value;
                this.RaisePropertyChanged("beneficiaryReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public enum transactionStatusTypeStatusCode {
        
        /// <remarks/>
        ONHOLD,
        
        /// <remarks/>
        SENT_TO_BENEFICIARY,
        
        /// <remarks/>
        COMPLETED,
        
        /// <remarks/>
        RETURNED_FROM_BENEFICIARY,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        SCHEDULED_FOR_NEXT_WORKDAY,
        
        /// <remarks/>
        IN_PROCESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public partial class contactType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileNoField;
        
        private string emailIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("mobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string emailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
                this.RaisePropertyChanged("emailID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum transferTypeType {
        
        /// <remarks/>
        NEFT,
        
        /// <remarks/>
        IMPS,
        
        /// <remarks/>
        FT,
        
        /// <remarks/>
        ANY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quantiguous.com/services")]
    public enum currencyCodeType {
        
        /// <remarks/>
        INR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class remitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string uniqueResponseNoField;
        
        private string attemptNoField;
        
        private string requestReferenceNoField;
        
        private transferTypeType transferTypeField;
        
        private bool lowBalanceAlertField;
        
        private transactionStatusType transactionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uniqueResponseNo {
            get {
                return this.uniqueResponseNoField;
            }
            set {
                this.uniqueResponseNoField = value;
                this.RaisePropertyChanged("uniqueResponseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string attemptNo {
            get {
                return this.attemptNoField;
            }
            set {
                this.attemptNoField = value;
                this.RaisePropertyChanged("attemptNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string requestReferenceNo {
            get {
                return this.requestReferenceNoField;
            }
            set {
                this.requestReferenceNoField = value;
                this.RaisePropertyChanged("requestReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public transferTypeType transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool lowBalanceAlert {
            get {
                return this.lowBalanceAlertField;
            }
            set {
                this.lowBalanceAlertField = value;
                this.RaisePropertyChanged("lowBalanceAlert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public transactionStatusType transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class remitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.remit remit;
        
        public remitRequest() {
        }
        
        public remitRequest(FormsApplication.com.quantiguous.remit remit) {
            this.remit = remit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class remitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.remitResponse remitResponse;
        
        public remitResponse1() {
        }
        
        public remitResponse1(FormsApplication.com.quantiguous.remitResponse remitResponse) {
            this.remitResponse = remitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBalance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string partnerCodeField;
        
        private string customerIDField;
        
        private string accountNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=1)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
                this.RaisePropertyChanged("partnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string accountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("accountNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getBalanceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private currencyCodeType accountCurrencyCodeField;
        
        private decimal accountBalanceAmountField;
        
        private bool lowBalanceAlertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public currencyCodeType accountCurrencyCode {
            get {
                return this.accountCurrencyCodeField;
            }
            set {
                this.accountCurrencyCodeField = value;
                this.RaisePropertyChanged("accountCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal accountBalanceAmount {
            get {
                return this.accountBalanceAmountField;
            }
            set {
                this.accountBalanceAmountField = value;
                this.RaisePropertyChanged("accountBalanceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool lowBalanceAlert {
            get {
                return this.lowBalanceAlertField;
            }
            set {
                this.lowBalanceAlertField = value;
                this.RaisePropertyChanged("lowBalanceAlert");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.getBalance getBalance;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(FormsApplication.com.quantiguous.getBalance getBalance) {
            this.getBalance = getBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.getBalanceResponse getBalanceResponse;
        
        public getBalanceResponse1() {
        }
        
        public getBalanceResponse1(FormsApplication.com.quantiguous.getBalanceResponse getBalanceResponse) {
            this.getBalanceResponse = getBalanceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getRemittanceStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string partnerCodeField;
        
        private string requestReferenceNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=1)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
                this.RaisePropertyChanged("partnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string requestReferenceNo {
            get {
                return this.requestReferenceNoField;
            }
            set {
                this.requestReferenceNoField = value;
                this.RaisePropertyChanged("requestReferenceNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getRemittanceStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private transferTypeType transferTypeField;
        
        private transferTypeType reqTransferTypeField;
        
        private System.DateTime transactionDateField;
        
        private decimal transferAmountField;
        
        private currencyCodeType transferCurrencyCodeField;
        
        private transactionStatusType transactionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public transferTypeType transferType {
            get {
                return this.transferTypeField;
            }
            set {
                this.transferTypeField = value;
                this.RaisePropertyChanged("transferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public transferTypeType reqTransferType {
            get {
                return this.reqTransferTypeField;
            }
            set {
                this.reqTransferTypeField = value;
                this.RaisePropertyChanged("reqTransferType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal transferAmount {
            get {
                return this.transferAmountField;
            }
            set {
                this.transferAmountField = value;
                this.RaisePropertyChanged("transferAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public currencyCodeType transferCurrencyCode {
            get {
                return this.transferCurrencyCodeField;
            }
            set {
                this.transferCurrencyCodeField = value;
                this.RaisePropertyChanged("transferCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public transactionStatusType transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
                this.RaisePropertyChanged("transactionStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRemittanceStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.getRemittanceStatus getRemittanceStatus;
        
        public getRemittanceStatusRequest() {
        }
        
        public getRemittanceStatusRequest(FormsApplication.com.quantiguous.getRemittanceStatus getRemittanceStatus) {
            this.getRemittanceStatus = getRemittanceStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRemittanceStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.getRemittanceStatusResponse getRemittanceStatusResponse;
        
        public getRemittanceStatusResponse1() {
        }
        
        public getRemittanceStatusResponse1(FormsApplication.com.quantiguous.getRemittanceStatusResponse getRemittanceStatusResponse) {
            this.getRemittanceStatusResponse = getRemittanceStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getTransactions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private string partnerCodeField;
        
        private string customerIDField;
        
        private string accountNoField;
        
        private dateRangeType dateRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", IsNullable=true, Order=1)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
                this.RaisePropertyChanged("partnerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string accountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("accountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public dateRangeType dateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
                this.RaisePropertyChanged("dateRange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quantiguous.com/services")]
    public partial class getTransactionsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private decimal openingBalanceField;
        
        private string numDebitsField;
        
        private string numCreditsField;
        
        private decimal closingBalanceField;
        
        private string numTransactionsField;
        
        private transactionType[] transactionsArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal openingBalance {
            get {
                return this.openingBalanceField;
            }
            set {
                this.openingBalanceField = value;
                this.RaisePropertyChanged("openingBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=2)]
        public string numDebits {
            get {
                return this.numDebitsField;
            }
            set {
                this.numDebitsField = value;
                this.RaisePropertyChanged("numDebits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=3)]
        public string numCredits {
            get {
                return this.numCreditsField;
            }
            set {
                this.numCreditsField = value;
                this.RaisePropertyChanged("numCredits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal closingBalance {
            get {
                return this.closingBalanceField;
            }
            set {
                this.closingBalanceField = value;
                this.RaisePropertyChanged("closingBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=5)]
        public string numTransactions {
            get {
                return this.numTransactionsField;
            }
            set {
                this.numTransactionsField = value;
                this.RaisePropertyChanged("numTransactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction", IsNullable=false)]
        public transactionType[] transactionsArray {
            get {
                return this.transactionsArrayField;
            }
            set {
                this.transactionsArrayField = value;
                this.RaisePropertyChanged("transactionsArray");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.getTransactions getTransactions;
        
        public getTransactionsRequest() {
        }
        
        public getTransactionsRequest(FormsApplication.com.quantiguous.getTransactions getTransactions) {
            this.getTransactions = getTransactions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.quantiguous.com/services", Order=0)]
        public FormsApplication.com.quantiguous.getTransactionsResponse getTransactionsResponse;
        
        public getTransactionsResponse1() {
        }
        
        public getTransactionsResponse1(FormsApplication.com.quantiguous.getTransactionsResponse getTransactionsResponse) {
            this.getTransactionsResponse = getTransactionsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DomesticRemittanceByPartnerServiceChannel : FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DomesticRemittanceByPartnerServiceClient : System.ServiceModel.ClientBase<FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService>, FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService {
        
        public DomesticRemittanceByPartnerServiceClient() {
        }
        
        public DomesticRemittanceByPartnerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DomesticRemittanceByPartnerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomesticRemittanceByPartnerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomesticRemittanceByPartnerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormsApplication.com.quantiguous.remitResponse1 FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.remit(FormsApplication.com.quantiguous.remitRequest request) {
            return base.Channel.remit(request);
        }
        
        public FormsApplication.com.quantiguous.remitResponse remit(FormsApplication.com.quantiguous.remit remit1) {
            FormsApplication.com.quantiguous.remitRequest inValue = new FormsApplication.com.quantiguous.remitRequest();
            inValue.remit = remit1;
            FormsApplication.com.quantiguous.remitResponse1 retVal = ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).remit(inValue);
            return retVal.remitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.remitResponse1> FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.remitAsync(FormsApplication.com.quantiguous.remitRequest request) {
            return base.Channel.remitAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormsApplication.com.quantiguous.remitResponse1> remitAsync(FormsApplication.com.quantiguous.remit remit) {
            FormsApplication.com.quantiguous.remitRequest inValue = new FormsApplication.com.quantiguous.remitRequest();
            inValue.remit = remit;
            return ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).remitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormsApplication.com.quantiguous.getBalanceResponse1 FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.getBalance(FormsApplication.com.quantiguous.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public FormsApplication.com.quantiguous.getBalanceResponse getBalance(FormsApplication.com.quantiguous.getBalance getBalance1) {
            FormsApplication.com.quantiguous.getBalanceRequest inValue = new FormsApplication.com.quantiguous.getBalanceRequest();
            inValue.getBalance = getBalance1;
            FormsApplication.com.quantiguous.getBalanceResponse1 retVal = ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).getBalance(inValue);
            return retVal.getBalanceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getBalanceResponse1> FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.getBalanceAsync(FormsApplication.com.quantiguous.getBalanceRequest request) {
            return base.Channel.getBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getBalanceResponse1> getBalanceAsync(FormsApplication.com.quantiguous.getBalance getBalance) {
            FormsApplication.com.quantiguous.getBalanceRequest inValue = new FormsApplication.com.quantiguous.getBalanceRequest();
            inValue.getBalance = getBalance;
            return ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).getBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormsApplication.com.quantiguous.getRemittanceStatusResponse1 FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.getRemittanceStatus(FormsApplication.com.quantiguous.getRemittanceStatusRequest request) {
            return base.Channel.getRemittanceStatus(request);
        }
        
        public FormsApplication.com.quantiguous.getRemittanceStatusResponse getRemittanceStatus(FormsApplication.com.quantiguous.getRemittanceStatus getRemittanceStatus1) {
            FormsApplication.com.quantiguous.getRemittanceStatusRequest inValue = new FormsApplication.com.quantiguous.getRemittanceStatusRequest();
            inValue.getRemittanceStatus = getRemittanceStatus1;
            FormsApplication.com.quantiguous.getRemittanceStatusResponse1 retVal = ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).getRemittanceStatus(inValue);
            return retVal.getRemittanceStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getRemittanceStatusResponse1> FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.getRemittanceStatusAsync(FormsApplication.com.quantiguous.getRemittanceStatusRequest request) {
            return base.Channel.getRemittanceStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getRemittanceStatusResponse1> getRemittanceStatusAsync(FormsApplication.com.quantiguous.getRemittanceStatus getRemittanceStatus) {
            FormsApplication.com.quantiguous.getRemittanceStatusRequest inValue = new FormsApplication.com.quantiguous.getRemittanceStatusRequest();
            inValue.getRemittanceStatus = getRemittanceStatus;
            return ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).getRemittanceStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormsApplication.com.quantiguous.getTransactionsResponse1 FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.getTransactions(FormsApplication.com.quantiguous.getTransactionsRequest request) {
            return base.Channel.getTransactions(request);
        }
        
        public FormsApplication.com.quantiguous.getTransactionsResponse getTransactions(FormsApplication.com.quantiguous.getTransactions getTransactions1) {
            FormsApplication.com.quantiguous.getTransactionsRequest inValue = new FormsApplication.com.quantiguous.getTransactionsRequest();
            inValue.getTransactions = getTransactions1;
            FormsApplication.com.quantiguous.getTransactionsResponse1 retVal = ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).getTransactions(inValue);
            return retVal.getTransactionsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getTransactionsResponse1> FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService.getTransactionsAsync(FormsApplication.com.quantiguous.getTransactionsRequest request) {
            return base.Channel.getTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormsApplication.com.quantiguous.getTransactionsResponse1> getTransactionsAsync(FormsApplication.com.quantiguous.getTransactions getTransactions) {
            FormsApplication.com.quantiguous.getTransactionsRequest inValue = new FormsApplication.com.quantiguous.getTransactionsRequest();
            inValue.getTransactions = getTransactions;
            return ((FormsApplication.com.quantiguous.DomesticRemittanceByPartnerService)(this)).getTransactionsAsync(inValue);
        }
    }
}
